# -*- coding: utf-8 -*-


MYSQL_USERNAME = 'socc'
MYSQL_PASSWORD = 'soccSecret'
MYSQL_HOST = 'localhost'
MYSQL_DATABASE = 'socc'

SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://{}:{}@{}/{}'.format(\
	MYSQL_USERNAME,MYSQL_PASSWORD,MYSQL_HOST,MYSQL_DATABASE)
SQLALCHEMY_TRACK_MODIFICATIONS = True

DEBUG = True
TESTING = False
SECRET_KEY = 'soccsocc1234'
SESSION_COOKIE_NAME = 'soccSessionId'